# Generated by Django 4.2.4 on 2023-10-23 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
