# Generated by Django 4.2.4 on 2023-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promition_productimage_product_prromition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prromition',
            new_name='promotion',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='P', max_length=1),
        ),
    ]
