# Generated by Django 4.2.4 on 2023-09-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_options_product_seller_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promition',
            new_name='Promotion',
        ),
    ]
