# Generated by Django 4.2.4 on 2023-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_number',
            field=models.IntegerField(default=0),
        ),
    ]
